kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - pytest

---
kind: pipeline
type: docker
name: publish

steps:
  - name: docker registry
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_ID
      password:
        from_secret: DOCKER_PASSWORD
      repo: mrrikkert/pymusic
      tags: latest
  - name: rancher
    image: peloton/drone-rancher
    settings:
      - url: https://rancher.kn01.fhict.nl/v3
      - access_key: ${RANCHER_ACCESS_KEY}
      - secret_key: ${RANCHER_SECRET_KEY}
      - docker_image: mrrikkert/pymusic
      - service: mrrikkert/pymusic
      - confirm: true

branch: master
depends_on:
  - test
