kind: pipeline
name: default

steps:
  # - name: set-commit-status-pending
  #   image: gboo/github-status

  - name: test
    image: python
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - pytest
      - echo hallo
