kind: pipeline
type: docker
name: test

steps:
  - name: test commit
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - pytest
    when:
      branch:
        exclude:
          - master

  - name: test full
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - export LASTFM_KEY=$LASTFM_KEY
      - export LASTFM_SECRET=$LASTFM_SECRET
      - pytest --run-optional-tests=lastfm
    environment:
      LASTFM_KEY:
        from_secret: LASTFM_KEY
      LASTFM_SECRET:
        from_secret: LASTFM_SECRET
    when:
      branch:
        - master

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: publish

steps:
  - name: docker registry
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_ID
      password:
        from_secret: DOCKER_PASSWORD
      repo: mrrikkert/pymusic
      tags: latest

trigger:
  branch:
    - master
  event:
    - push
depends_on:
  - test
