kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: python:3.8
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - pytest

---
kind: pipeline
type: docker
name: registry

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_ID
      password:
        from_secret: DOCKER_PASSWORD
      repo: mrrikkert/pymusic
      tags: latest

depends_on:
  - test
