kind: pipeline
type: docker
name: test

steps:
  # Testen die uitgevoerd worden bij een normale commit
  - name: test commit
    image: python:3.8
    environment:
      MUSIC_PATH: Y:\Music
      LIBRARY_BASE_PATH: Y:\Music
    commands:
      - pip install -r requirements.dev.txt
      - pytest
      - flake8
      - autoflake -r --remove-all-unused-imports --remove-unused-variables .
      - isort . -c
    when:
      branch:
        exclude:
          - master

  # Deze testen worden bij commits/pull requests op master uitgevoerd
  - name: test full
    image: python:3.8
    environment:
      MUSIC_PATH: Y:\Music
      LIBRARY_BASE_PATH: Y:\Music
      # Deze secrets staan gedefinieerd in de drone server
      LASTFM_KEY:
        from_secret: LASTFM_KEY
      LASTFM_SECRET:
        from_secret: LASTFM_SECRET
    commands:
      - pip install -r requirements.dev.txt
      # Zet de benodigde env variabelen in de sessie
      # deze worden opgepakt door de applicatie
      - export LASTFM_KEY=$LASTFM_KEY
      - export LASTFM_SECRET=$LASTFM_SECRET
      # Draai ook de lastfm network tests
      - pytest --run-optional-tests=lastfm
      - flake8
      - autoflake -r --remove-all-unused-imports --remove-unused-variables .
      - isort . -c
    when:
      branch:
        - master

trigger:
  event:
    - push
    - pull_request
