kind: pipeline
name: default

steps:
  - name: test
    image: python
    commands:
      - pip install pipenv
      - pipenv install --system --deploy --dev --ignore-pipfile
      - pytest --run-optional-tests=lastfm
