FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

RUN pip install pipenv

COPY Pipfile.lock .
COPY Pipfile .

RUN pipenv install --system --deploy --ignore-pipfile

ENV JWT_SECRET_KEY=
ENV JWT_ALGORITHM=
ENV PASS_ALGORITHM=
ENV LASTFM_KEY=
ENV LASTFM_SECRET=
ENV DB_PROVIDER=
ENV DB_SQLITE_FILENAME=
ENV DB_SQLITE_CREATE_DB=
ENV DB_POSTGRES_USER=
ENV DB_POSTGRES_PASSWORD=
ENV DB_POSTGRES_HOST=
ENV DB_POSTGRES_DATABASE=

COPY . /app
