# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "pip"
    - name: Install Poetry
      run: |
        export POETRY_HOME=/opt/poetry
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.2.0
        $POETRY_HOME/bin/poetry --version
    - name: Install dependencies
      run: |
        export POETRY_HOME=/opt/poetry
        $POETRY_HOME/bin/poetry config virtualenvs.create false
        $POETRY_HOME/bin/poetry install --with dev
    - name: Lint
      run: |
        flake8
        autoflake -r --remove-all-unused-imports --remove-unused-variables .
        isort . -c
    - name: Test
      run: |
        pytest
    - name: Test optionals
      env:
        LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
        LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}
      if: github.ref == 'refs/heads/master'
      run: |
        pytest -m lastfm
